apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-deployment
    labels:
        name: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            name: redis
    template:
        metadata:
            labels:
                name: redis
        spec:
            subdomain: primary
            containers:
                - name: redis
                  image: redis:6.2.5
                  command:
                      - 'redis-server'
                  args:
                      - '--protected-mode'
                      - 'no'
                  ports:
                      - containerPort: 6379
