apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-server-redis
    labels:
        name: auth-server
        tier: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth-server
            tier: redis
    template:
        metadata:
            labels:
                app: auth-server
                tier: redis
        spec:
            subdomain: primary
            containers:
                - name: redis
                  image: redis:6.2.5
                  command:
                      - 'redis-server'
                  args:
                      - '--protected-mode'
                      - 'no'
                  ports:
                      - containerPort: 6379
