apiVersion: v1
kind: Service
metadata:
    name: auther-server-redis
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
          name: redis
    selector:
        app: auth-server
        tier: redis
