apiVersion: skaffold/v2beta18
kind: Config
metadata:
    name: auth-server
build:
    artifacts:
        - image: auth-server
          docker:
              dockerfile: Dockerfile
deploy:
    kustomize:
        paths:
            - k8s/base
profiles:
    - name: test
      deploy:
          kustomize:
              paths:
                  - k8s/overlays/test
    - name: qa
      build:
          artifacts:
              - image: hargwit/auth-server
                docker:
                    dockerfile: Dockerfile
      deploy:
          kustomize:
              paths:
                  - k8s/overlays/qa
    - name: production
      build:
          artifacts:
              - image: hargwit/auth-server
                docker:
                    dockerfile: Dockerfile
      deploy:
          kustomize:
              paths:
                  - k8s/overlays/production
