apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: auth-server
build:
  artifacts:
  - image: auth-server
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: auth-server
  deploy:
    kustomize:
      paths:
      - k8s/base/auth-server
- name: mysql
  deploy:
    kustomize:
      paths:
      - k8s/base/mysql
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
