apiVersion: v1
kind: Service
metadata:
    name: auth-server-mysql
    labels:
        app: auth-server
spec:
    ports:
        - port: 3306
    selector:
        app: auth-server
        tier: mysql
    clusterIP: None
