apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: auth-ingress
    annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: auth-server-ssl
spec:
    tls:
        - hosts:
              - auth.hargwit.com
          secretName: auth-server-ssl
    rules:
        - host: auth.hargwit.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: auth-server
                            port:
                                number: 80
