apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-server-backend
    app: auth-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth-server
            tier: backend
    template:
        metadata:
            labels:
                app: auth-server
                tier: backend
        spec:
            containers:
                - name: auth-server
                  image: auth-server
                  ports:
                      - containerPort: 3000
