apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: auth-server-tls
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: harrygwithers@gmail.com
        privateKeySecretRef:
            name: auth-server-tls
        solvers:
            - http01:
                  ingress:
                      class: nginx
