apiVersion: certmanager.io/v1
kind: ClusterIssuer
metadata:
    name: auth-server-ssl
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: harrygwithers@gmail.com
        privateKeySecretRef:
            name: auth-server-ssl
        http01: {}
