apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa

bases:
    - ../../base

images:
    - name: auth-server
      newName: hargwit/auth-server

resources:
    - namespace.yaml
