on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_USER: ${{ secrets.MYSQL_TEST_USER }}
                    MYSQL_PASSWORD: ${{ secrets.MYSQL_TEST_PASSWORD }}
                    MYSQL_DATABASE: ${{ secrets.MYSQL_TEST_DATABASE }}
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_TEST_ROOT_PASSWORD }}
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

            redis:
                image: redis
                ports:
                    - 6379:6379
                options: --entrypoint redis-server

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Install depedencies
              run: npm ci

            - name: build
              run: npm run build

            - name: test
              run: npm run test-int
              env:
                  REDIS_HOST: redis
                  REDIS_PORT: ${{ job.services.redis.ports[6379] }}
                  MYSQL_HOST: mysql
                  MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
                  MYSQL_USER: ${{ secrets.MYSQL_TEST_USER }}
                  MYSQL_PASSWORD: ${{ secrets.MYSQL_TEST_PASSWORD }}
                  MYSQL_DATABASE: ${{ secrets.MYSQL_TEST_DATABASE }}
                  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_TEST_ROOT_PASSWORD }}
