on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_USER: root
                    MYSQL_PASSWORD: password
                    MYSQL_DATABASE: auth
                    MYSQL_ROOT_PASSWORD: password
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

            redis:
                image: redis
                ports:
                    - 6379:6379
                options: --entrypoint redis-server

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Install depedencies
              run: npm ci

            - name: test
              run: npm run test-int
              env:
                  REDIS_HOST: redis
                  REDIS_PORT: ${{ job.services.redis.ports[6379] }}
                  MYSQL_HOST: mysql
                  MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
                  MYSQL_USER: ${{ job.services.mysql.env[MYSQL_USER] }}
                  MYSQL_PASSWORD: ${{ job.services.mysql.env[MYSQL_PASSWORD] }}
