on: pull_request

jobs:
    integration-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup DNS
              run: sudo echo "127.0.0.1 auth-test.hargwit.com" >> /etc/hosts

            - uses: actions/setup-go@v1
              with:
                  go-version: 1.13

            - name: Install Kind
              run: GO111MODULE=on go get sigs.k8s.io/kind

            - name: Install Skaffold
              run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/

            - name: Build cluster
              run: PATH=$(go env GOPATH)/bin:$PATH ./k8s/create-cluster.sh ./k8s/cluster-config.yaml

            - name: Deploy to Kind
              run: skaffold run -p test

            - name: Install depedencies
              run: npm ci

            - name: Test
              run: npm run test-int
              env:
                  APP_URL: http://auth-test.hargwit.com
