# on:
#     release:
#         types: [created]

on:
    branches: [ci/deploy]

env:
    PROJECT_ID: ${{ secrets.GKE_PROJECT }}
    GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
    GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.GKE_PROJECT }}
                  service_account_key: ${{ secrets.GKE_SA_KEY }}

            - name: Use gcloud CLI
              run: gcloud info
