on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Install depedencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test-unit

            - name: Build
              run: npm run build

    integration-test:
        runs-on: ubuntu-latest
        container:
            image: gcr.io/k8s-skaffold/skaffold:v1.15.0
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - uses: actions/setup-go@v1
              with:
                go-version: 1.13

            - name: Install Kind
                run: |
                  GO111MODULE=on go get sigs.k8s.io/kind

            - name: Build cluster
              run: PATH=$(go env GOPATH)/bin:$PATH k8s/dev/create-cluster.sh

            - name: Deploy app
              run: skaffold run

            - name: Install depedencies
              run: npm ci

            - name: Test
              run: npm run test-int
              env:
                  APP_URL: http://localhost:80
